name = "SegmentedReassortmentGraphs"
uuid = "6ed0fea0-dd32-4570-8b49-0116ace4057e"
authors = ["Pierre Barrat-Charlaix"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
